# Generated by Django 3.2.9 on 2021-12-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tecnico',
            field=models.BooleanField(blank=True, default=' '),
            preserve_default=False,
        ),
    ]
