# Generated by Django 3.2.9 on 2021-11-05 20:46

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('placa_patrimonio', models.IntegerField()),
                ('local', models.CharField(max_length=100)),
                ('problema', models.TextField(max_length=300)),
                ('horarioInsercao', models.DateTimeField()),

            ],
        ),
    ]
