# Generated by Django 3.2.9 on 2021-11-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_osrm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lista',
            new_name='InserirDados',
        ),
    ]
