# Generated by Django 3.2.9 on 2021-11-17 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_osrm', '0002_rename_lista_inserirdados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserirdados',
            name='horarioInsercao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
