# Generated by Django 3.2.9 on 2021-11-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_osrm', '0005_alter_inserirdados_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserirdados',
            name='placa_patrimonio',
            field=models.IntegerField(null=True),
        ),
    ]
