# Generated by Django 3.2.9 on 2021-11-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_osrm', '0007_alter_inserirdados_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserirdados',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
